name: letter_recognition_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  fast_image_resizer: ^0.0.2
  flutter:
    sdk: flutter
  pixels:
    path: packages/pixels
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
